### ISSUE TITLE
add: notification system

### ISSUE THREAD

**Issue by mishelashala** [ksquarelabsmx/conference-client#24]
<img width="345" alt="screen shot 2019-03-07 at 10 55 47" src="https://user-images.githubusercontent.com/5624153/53974143-a1e01e80-40c7-11e9-9828-225e9eb81d88.png">
<img width="1111" alt="screen shot 2019-03-07 at 10 56 01" src="https://user-images.githubusercontent.com/5624153/53974144-a1e01e80-40c7-11e9-9487-7bbdc5484c53.png">

events:
- booking created/cancelled/edited

**Comment by basultobdKs** [comment]
Completed in #71
