### ISSUE TITLE
when the user is not logged in NavBar crashesh the app

### ISSUE THREAD

**Issue by mishelashala** [ksquarelabsmx/conference-client#39]
`NavBar` tries to access the user info, but it is a nested property inside a nested (possibly null) object.

One solution is to use monads, ([see](https://jrsinclair.com/articles/2016/marvellously-mysterious-javascript-maybe-monad/) for reference), but that approach is an over-kill rn.

Currently we're using `lodash`, which has a `functional` part. So we can use `prop`, `compose` and `defaultTo`.

```js
const data = {
  sessionInfo: {
    user: {
      name: 'John Doe'
    }
  }
}

// getUserName :: ISessionInfo -> String
const getUserName = fp.compose(
  fp.defaultTo(''),
  fp.prop('name'),
  fp.prop('user'),
  fp.prop('sessionInfo')
)

getUserName(data) // 'John Doe'

// it doesn't crash, yay!
getUserName({}) // ''
```

**Comment by basultobdKs** [comment]
Completed in #50
